# Generated by Django 3.2.8 on 2022-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
