# Generated by Django 3.2.8 on 2022-02-25 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220224_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 2, 25, 5, 54, 9, 453064, tzinfo=utc)),
        ),
    ]
